### ISSUE TITLE
Game still running at 60fps

### ISSUE THREAD

**Issue by thelocal-spider** [cipherxof/MGSFPSUnlock#5]
The version of the game is pirated, however, the mod doesn't work on Windows or through Wine on Linux. Other mods such as MGSHDFix works, however. Would love to play this game with 30fps as the system is low end. Hopefully there's a fix for this, thanks!

**Comment by mgsfox** [comment]
What version do you have?

**Comment by thelocal-spider** [comment]
Not quite sure, but the file I downloaded was from October so I'd say it's release version

**Comment by cipherxof** [comment]
This mod doesn't work on patch 1.0.

**Comment by thelocal-spider** [comment]
Update : mod works great on 1.3.0, except the audio seems to be sort of bugged at times, like the codec ringtone, and going into the radio menu takes a bit longer

**Comment by thelocal-spider** [comment]
Great work on the mod, man! It's awesome for lower end devices who just wanna enjoy the game
